name: Docker Build

on:
  pull_request:
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - ".dockerignore"
      - "package.json"
      - "package-lock.json"
      - "src/**"

jobs:
  docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: discord-ai-bot:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
